various changes in different contexts

diff --git a/scripts/install_local_hdf5 b/scripts/install_local_hdf5
--- a/scripts/install_local_hdf5
+++ b/scripts/install_local_hdf5
@@ -47,7 +47,9 @@ do
     h)  descript
         exit ;;
     q)  QUIET=t ;;
-    -)  if [ "${UOPTARG%=*}" = DEBUG ] ; then
+    -)  if [ "${UOPTARG%=*}" = CURR_SRC ] ; then
+           currSrc=${QA_PATH}/local/source/${OPTARG#*=}
+        elif [ "${UOPTARG%=*}" = DEBUG ] ; then
            test "${UOPTARG}" = DEBUG -o ${OPTARG#*=} = ${0##*/} && set -x
         elif [ "$UOPTARG" = DISTCLEAN ] ; then
            isDistClean=t
@@ -66,10 +68,8 @@ done
 
 shift $(( $OPTIND - 1 ))
 
-src=$installPath/source
-
-if [ -d "${src}" ] ; then
-  cd $src &> /dev/null
+if [ -d $currSrc ] ; then
+  cd ${currSrc} &> /dev/null
 else
   exit 1
   return
@@ -94,24 +94,25 @@ fi
 test $? -gt 0 && exit 1
 
 if ! make  >>${out} 2>&1 ; then
-  echo "${src##*/}: make failed" 1>&2
+  echo "${currSrc##*/}: make failed" 1>&2
   exit 2
 fi
 
 if ! make check  >>${out} 2>&1 ; then
-  echo "${src##*/}: make check failed" 1>&2
+  echo "${currSrc##*/}: make check failed" 1>&2
   exit 3
 fi           # run test suite.
 
 if ! make install  >>${out} 2>&1 ; then
-  echo "${src##*/}: make install failed"  1>&2
+  echo "${currSrc##*/}: make install failed"  1>&2
   exit 4
 fi
 
 if ! make check-install  >>${out} 2>&1  ; then
-  echo "${src##*/}: make check-install failed" 1>&2
+  echo "${currSrc##*/}: make check-install failed" 1>&2
   exit 5
 fi  # verify installation
 
+date > $currSrc/QA_Compilation
 
 exit 0
diff --git a/scripts/install_local_netcdf b/scripts/install_local_netcdf
--- a/scripts/install_local_netcdf
+++ b/scripts/install_local_netcdf
@@ -69,7 +69,9 @@ do
     h)  descript
         exit ;;
     q)  QUIET=t ;;
-    -)  if [ "${UOPTARG%%=*}" = PREFIX ] ; then
+    -)  if [ "${UOPTARG%=*}" = CURR_SRC ] ; then
+           currSrc=${QA_PATH}/local/source/${OPTARG#*=}
+        elif [ "${UOPTARG%%=*}" = PREFIX ] ; then
            prefix=${OPTARG#*=}
         elif [ "$UOPTARG" = HELP ] ; then
            descript
@@ -87,10 +89,8 @@ done
 
 shift $(( $OPTIND - 1 ))
 
-src=$installPath/source
-
-if [ -d "$src" ] ; then
-  cd $src &> /dev/null
+if [ -d $currSrc ] ; then
+  cd ${currSrc} &> /dev/null
 else
   exit 1
   return
@@ -106,14 +106,16 @@ fi
 
 if ! c ; then
   status=$?
-  echo "${src##*/}: configure failed"
-  exit $status
+  echo "${currSrc##*/}: configure failed"
+  exit 1
 fi
 
 if ! make check install  >>${out} 2>&1 ; then
   status=$?
-  echo "${src##*/}: make check install failed"
-  exit $status
+  echo "${currSrc##*/}: make check install failed"
+  exit 1
 fi
+
+date > $currSrc/QA_Compilation
 
 exit 0
